### ISSUE TITLE
suggestion: pass webmap item id into startup()

### ISSUE THREAD

**Issue by tomwayson** [odoe/jsapi-react-template#2]
I think it would be good to pass the web map id as an argument like `startup(mapDiv, itemId)` so that it’s not hard-coded here:

https://github.com/odoe/jsapi-react-template/blob/6945dfb02d7ba79734488b0db9d6eb9a00248f67/src/data/map.ts#L8

Or maybe `import` it from a config file? Putting it some place along side other things that the user would want to change (like app title, etc).

**Comment by odoe** [comment]
added a config
